[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags = -std=gnu++17
lib_deps = adafruit/Adafruit PWM Servo Driver Library

[env:native]
platform = native
build_flags = -std=c++17
test_filter = test_native
build_src_filter = -<src/>
